LOAD DATA LOCAL INFILE 'Author1.csv'
INTO TABLE Author
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'Publisher1.csv'
INTO TABLE Publisher
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'Members1.csv'
INTO TABLE Member
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'Book1.csv'
INTO TABLE Book
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'Phone1.csv'
INTO TABLE Phone
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'Publisher1.csv'
INTO TABLE Publisher
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'publisherPhone1.csv'
INTO TABLE publisherPhone
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'authorPhone1.csv'
INTO TABLE authorPhone
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'borrowedby1.csv'
INTO TABLE borrowedby
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';

UPDATE borrowedby SET Checkin_Date=NULL WHERE Checkin_Date="0000-00-00";

LOAD DATA LOCAL INFILE 'writtenby1.csv'
INTO TABLE writtenby
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'Library1.csv'
INTO TABLE Library
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'locatedat1.csv'
INTO TABLE locatedat
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';

SET FOREIGN_KEY_CHECKS = 0;
LOAD DATA LOCAL INFILE 'publishedby1.csv'
INTO TABLE publishedby
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
SET FOREIGN_KEY_CHECKS = 1;

UPDATE locatedat
INNER JOIN
	checkedout ON locatedat.ISBN=checkedout.ISBN
SET
	Copies_Not_Checked_Out = Copies_Not_Checked_Out - 1
WHERE
	locatedat.Name="Main";